// scripts/recapture-demo-sessions.ts — re-run Ana, Carmen, and the 4
// cohort-fill sessions after the Unit I–III prompts were rewritten to be
// program-style. Exercises themselves are NOT touched; their scaffolding
// was already regenerated by rescaffold-prompts.ts.
//
// Beto (password-demo, Unit IV, unchanged) is preserved.

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "../src/lib/db";
import { callOpusAndParse } from "../src/lib/opus/client";
import {
  SPEC_EXAMINER_SYSTEM,
  buildSpecExaminerUserMessage,
} from "../src/lib/opus/prompts/spec-examiner";
import {
  INTENT_DIFF_SYSTEM,
  buildIntentDiffUserMessage,
} from "../src/lib/opus/prompts/intent-diff";
import {
  POST_HOC_SYSTEM,
  buildPostHocUserMessage,
} from "../src/lib/opus/prompts/post-hoc";
import {
  IntentDiffOutput,
  Phase1Data,
  Phase1Iteration,
  PostHocOutput,
  SpecExaminerOutput,
  intentDiffOutputToDivergences,
  type ExerciseRecord,
} from "../src/lib/opus/schemas";
import {
  advancePhase,
  appendHelpRequest,
  appendPhase1Iteration,
  createSession,
  finalizePhase2Code,
  getExercise,
  getSession,
  recordDivergenceResponse,
  setPhase3Divergences,
} from "../src/lib/sessions";
import { refreshSummaryForSession } from "../src/lib/opus/summaries";

const AFFECTED_STUDENTS = [
  "ana_student",
  "carmen_student",
  "cohort_student_0",
  "cohort_student_1",
  "cohort_student_2",
  "cohort_student_3",
];

const FIXTURE_DIR = path.join(process.cwd(), "tests", "fixtures", "sessions");

async function wipeAffectedSessions() {
  const rows = await prisma.session.findMany({
    where: { studentId: { in: AFFECTED_STUDENTS } },
    select: { id: true, studentId: true, exerciseId: true },
  });
  console.log(`Wiping ${rows.length} existing affected sessions…`);
  const ids = rows.map((r) => r.id);
  await prisma.sessionEvent.deleteMany({ where: { sessionId: { in: ids } } });
  await prisma.session.deleteMany({ where: { id: { in: ids } } });

  // Also delete the fixture JSONs so exportSessionFixtures writes clean.
  for (const id of ids) {
    const p = path.join(FIXTURE_DIR, `${id}.json`);
    try {
      await fs.unlink(p);
    } catch {
      /* fine if not present */
    }
  }
}

async function runSpecIteration(
  sessionId: string,
  exercise: ExerciseRecord,
  specText: string,
) {
  const session = await getSession(sessionId);
  const priorIterations = Phase1Data.parse(session.phase1Data).iterations;
  const examiner = await callOpusAndParse({
    promptName: "recapture:spec-examiner",
    system: SPEC_EXAMINER_SYSTEM,
    messages: [
      {
        role: "user",
        content: buildSpecExaminerUserMessage(exercise, priorIterations, specText),
      },
    ],
    maxTokens: 1024,
    schema: SpecExaminerOutput,
  });
  const iter: Phase1Iteration = {
    timestamp: new Date().toISOString(),
    studentSpecText: specText,
    opusQuestions: examiner.questions,
    gapsIdentified: examiner.gaps_still_open,
    gapsAddressedThisRound: examiner.gaps_addressed,
    emergentGaps: examiner.emergent_gaps,
    passed: examiner.gaps_still_open.length === 0,
  };
  await appendPhase1Iteration(sessionId, iter);
  return iter;
}

// ─── Ana — Unit II / vowels drift (closed) ────────────────────────────────
async function recaptureAna() {
  console.log("\n[ana] vowels drift (program-style)");
  const vowels = await getExercise("vowels-demo");
  const session = await createSession("vowels-demo", "ana_student");

  const r1 = await runSpecIteration(
    session.id,
    vowels,
    "The program asks the user for a string and prints the number of vowels in it.",
  );
  console.log(`  round 1: passed=${r1.passed}, open=[${r1.gapsIdentified.join(", ")}]`);

  const r2 = await runSpecIteration(
    session.id,
    vowels,
    "The program asks the user for a string with input() and prints just the integer count of vowels (no accompanying text). Vowels are both lowercase a,e,i,o,u and uppercase A,E,I,O,U. 'y' is not a vowel. If the user enters an empty string, it prints 0.",
  );
  console.log(`  round 2: passed=${r2.passed}, open=[${r2.gapsIdentified.join(", ")}]`);

  if (!r2.passed) {
    const r3 = await runSpecIteration(
      session.id,
      vowels,
      `${r2.studentSpecText}\n\nExplicit commitments: ${r2.gapsIdentified.map((g) => `'${g}' is handled above`).join(", ")}.`,
    );
    console.log(`  round 3: passed=${r3.passed}`);
    if (!r3.passed) throw new Error("ana didn't close spec in 3 rounds");
  }

  await advancePhase(session.id, 2);

  // Lowercase-only drift code — program style.
  const droppedCode = `s = input("Enter a string: ")
count = 0
for c in s:
    if c in 'aeiou':
        count = count + 1
print(count)
`;
  await finalizePhase2Code(session.id, droppedCode);

  const loaded = await getSession(session.id);
  const phase2 = {
    opusExchanges: [],
    revisions: [],
    currentCode: droppedCode,
    finalCode: droppedCode,
    submittedAt: new Date().toISOString(),
  };
  const diff = await callOpusAndParse({
    promptName: "recapture:intent-diff",
    system: INTENT_DIFF_SYSTEM,
    messages: [
      {
        role: "user",
        content: buildIntentDiffUserMessage({
          exercise: vowels,
          phase1: Phase1Data.parse(loaded.phase1Data),
          phase2,
        }),
      },
    ],
    maxTokens: 4096,
    schema: IntentDiffOutput,
  });
  const divergences = intentDiffOutputToDivergences(diff);
  await setPhase3Divergences(session.id, divergences);
  await advancePhase(session.id, 3);
  console.log(`  intent-diff: ${divergences.length} divergences`);

  for (const d of divergences) {
    const answer =
      d.initialClassification === "drift"
        ? "I forgot about the capital letters."
        : "I don't know.";
    const postHoc = await callOpusAndParse({
      promptName: "recapture:post-hoc",
      system: POST_HOC_SYSTEM,
      messages: [
        {
          role: "user",
          content: buildPostHocUserMessage({
            studentLevel: vowels.studentLevel,
            initialClassification: d.initialClassification,
            predictedJustification: d.predictedJustification,
            studentResponse: answer,
          }),
        },
      ],
      maxTokens: 512,
      schema: PostHocOutput,
    });
    await recordDivergenceResponse(
      session.id,
      d.divergenceId,
      answer,
      postHoc.alignment,
      postHoc.final_classification,
      postHoc.final_classification_reason,
    );
  }
  const s = await getSession(session.id);
  if (!s.completedAt) await advancePhase(session.id, 4);

  await refreshSummaryForSession(session.id);
  return session.id;
}

// ─── Carmen — Unit III / fibonacci stuck (open) ──────────────────────────
async function recaptureCarmen() {
  console.log("\n[carmen] fibonacci stuck (program-style)");
  const fib = await getExercise("fibonacci-demo");
  const session = await createSession("fibonacci-demo", "carmen_student");

  const tries = [
    "The program asks the user for a number and prints the nth Fibonacci number.",
    "The program asks the user for an integer n and prints the nth Fibonacci number. It handles negative input appropriately.",
    "The program asks for an integer n >= 0 and prints the nth Fibonacci number (fib(0) = 0, fib(1) = 1). Negative inputs are handled.",
  ];
  for (let i = 0; i < tries.length; i++) {
    const iter = await runSpecIteration(session.id, fib, tries[i]);
    console.log(`  round ${i + 1}: passed=${iter.passed}, open=[${iter.gapsIdentified.join(", ")}]`);
    if (iter.passed) {
      console.log("  unexpectedly passed — carmen is supposed to stay stuck");
      break;
    }
  }

  await appendHelpRequest(session.id, {
    timestamp: new Date().toISOString(),
    stateAtRequest: { phase: 1, attemptNumber: 3 },
    message:
      "I don't understand what 'handles negative input appropriately' is supposed to mean. Can someone come explain?",
    resolution: null,
  });

  const summary = await refreshSummaryForSession(session.id);
  console.log(`  live summary: ${summary?.summaryText}`);
  return session.id;
}

// ─── Cohort fill — 4 Unit II vowel sessions ──────────────────────────────
async function recaptureCohortFill() {
  console.log("\n[cohort-fill] 4 additional vowels sessions (program-style)");
  const vowels = await getExercise("vowels-demo");
  const specs = [
    // Three with case-drift patterns in the CODE
    "The program asks for a string with input() and prints just the integer count of vowels (no extra text). Counts lowercase aeiou and uppercase AEIOU. 'y' is not a vowel. Empty input → prints 0.",
    "Reads a string with input() and prints the number of vowels — just the number, nothing else. Counts a,e,i,o,u and A,E,I,O,U. y is not counted. Empty string → prints 0.",
    "Asks for a string via input(). Prints just the integer count of vowels (both lowercase aeiou and uppercase AEIOU, 'y' not counted). Empty string → prints 0.",
    // One clean (no drift)
    "Asks the user for a string with input(), then prints the number of vowels as a single integer with no extra message (lowercase aeiou AND uppercase AEIOU, 'y' is NOT a vowel). Empty string → prints 0.",
  ];
  const codesWithDrift = [
    // drift: only checks lowercase
    `s = input()
count = 0
for c in s:
    if c in 'aeiou':
        count += 1
print(count)
`,
    `text = input()
total = 0
for ch in text:
    if ch in 'aeiou':
        total = total + 1
print(total)
`,
    `print(sum(1 for c in input() if c in 'aeiou'))
`,
  ];
  const cleanCode = `print(sum(1 for c in input() if c in 'aeiouAEIOU'))
`;
  const answers = [
    "I forgot about the capital letters.",
    "I didn't think about uppercase.",
    "I guess I forgot to add the uppercase ones.",
    "",
  ];

  for (let i = 0; i < 4; i++) {
    const session = await createSession("vowels-demo", `cohort_student_${i}`);
    const iter = await runSpecIteration(session.id, vowels, specs[i]);
    if (!iter.passed) {
      console.log(`  cohort ${i}: spec didn't pass in 1 round; open=[${iter.gapsIdentified.join(", ")}]`);
      // Try once more with everything.
      await runSpecIteration(
        session.id,
        vowels,
        `${specs[i]}\n\nExplicit commitments for ${iter.gapsIdentified.join(", ")}.`,
      );
    }
    await advancePhase(session.id, 2);
    const code = i < 3 ? codesWithDrift[i] : cleanCode;
    await finalizePhase2Code(session.id, code);

    const loaded = await getSession(session.id);
    const phase2 = {
      opusExchanges: [],
      revisions: [],
      currentCode: code,
      finalCode: code,
      submittedAt: new Date().toISOString(),
    };
    const diff = await callOpusAndParse({
      promptName: "recapture:intent-diff",
      system: INTENT_DIFF_SYSTEM,
      messages: [
        {
          role: "user",
          content: buildIntentDiffUserMessage({
            exercise: vowels,
            phase1: Phase1Data.parse(loaded.phase1Data),
            phase2,
          }),
        },
      ],
      maxTokens: 4096,
      schema: IntentDiffOutput,
    });
    const divergences = intentDiffOutputToDivergences(diff);
    await setPhase3Divergences(session.id, divergences);
    await advancePhase(session.id, 3);
    console.log(`  cohort ${i}: ${divergences.length} divergences`);

    for (const d of divergences) {
      const postHoc = await callOpusAndParse({
        promptName: "recapture:post-hoc",
        system: POST_HOC_SYSTEM,
        messages: [
          {
            role: "user",
            content: buildPostHocUserMessage({
              studentLevel: vowels.studentLevel,
              initialClassification: d.initialClassification,
              predictedJustification: d.predictedJustification,
              studentResponse: answers[i],
            }),
          },
        ],
        maxTokens: 512,
        schema: PostHocOutput,
      });
      await recordDivergenceResponse(
        session.id,
        d.divergenceId,
        answers[i],
        postHoc.alignment,
        postHoc.final_classification,
        postHoc.final_classification_reason,
      );
    }
    const s = await getSession(session.id);
    if (!s.completedAt) await advancePhase(session.id, 4);
  }
}

// ─── Export ──────────────────────────────────────────────────────────────

async function exportSessionFixtures() {
  await fs.mkdir(FIXTURE_DIR, { recursive: true });
  const sessions = await prisma.session.findMany({ include: { events: true } });
  for (const s of sessions) {
    await fs.writeFile(
      path.join(FIXTURE_DIR, `${s.id}.json`),
      JSON.stringify(s, null, 2),
    );
  }
  return sessions.length;
}

async function main() {
  await wipeAffectedSessions();
  await recaptureAna();
  await recaptureCarmen();
  await recaptureCohortFill();
  const count = await exportSessionFixtures();
  console.log(`\nRe-exported ${count} session fixtures.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
